// base modules
import 'react'
import 'react-native'
import 'prop-types'
// import 'react-redux'
// import 'redux'
// import 'redux-thunk'
// import 'react-navigation'
// import 'react-native-cookies'
// import 'react-native-picker'
// import 'antd-mobile'
// import 'seamless-immutable'
// import 'key-mirror'
import './resolveInject'